S3_LOG_URI = '/cloudml/logs'
AMAZON_ACCESS_TOKEN = 'FILL ME'
AMAZON_TOKEN_SECRET = 'FILL ME'
BUCKET_NAME = 'BUCKET NAME'
DEFAILT_AMI_VERSION = '3.1.0'
DEFAULT_INSTANCE_TYPE = 'm1.small'
DEFAULT_NUM_INSTANCES = 1
