S3_LOG_URI = '/cloudml/logs'
AMAZON_ACCESS_TOKEN = 'AKIAJYNNIPFWF2ABW42Q---'
AMAZON_TOKEN_SECRET = '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---'
BUCKET_NAME = 'odesk-match-prod'
DEFAILT_AMI_VERSION = '3.1.0'
DEFAULT_INSTANCE_TYPE = 'm1.small'
DEFAULT_NUM_INSTANCES = 1
